// ===============================
// AIVANA YouTube Backend (FINAL)
// Phase 1 + Phase 2
// ===============================

import express from "express";
import fs from "fs";
import path from "path";
import multer from "multer";
import dotenv from "dotenv";
import { google } from "googleapis";

dotenv.config();

const app = express();
app.use(express.json());

// ===============================
// ENV + PORT
// ===============================
const PORT = process.env.PORT || 10000;
const CLIENT_ID = process.env.YOUTUBE_CLIENT_ID;
const CLIENT_SECRET = process.env.YOUTUBE_CLIENT_SECRET;
const REDIRECT_URI = process.env.YOUTUBE_REDIRECT_URI;

// ===============================
// UPLOADS DIR
// ===============================
const UPLOAD_DIR = path.join(process.cwd(), "uploads");
if (!fs.existsSync(UPLOAD_DIR)) {
  fs.mkdirSync(UPLOAD_DIR);
}

// ===============================
// MULTER CONFIG
// ===============================
const upload = multer({ dest: UPLOAD_DIR });

// ===============================
// GOOGLE OAUTH CLIENT
// ===============================
const oauth2Client = new google.auth.OAuth2(
  CLIENT_ID,
  CLIENT_SECRET,
  REDIRECT_URI
);

// ===============================
// LOAD TOKENS IF EXIST
// ===============================
const TOKEN_PATH = path.join(process.cwd(), "tokens.json");
if (fs.existsSync(TOKEN_PATH)) {
  const tokens = JSON.parse(fs.readFileSync(TOKEN_PATH, "utf8"));
  oauth2Client.setCredentials(tokens);
}

// ===============================
// AUTH ROUTE
// ===============================
app.get("/auth", (req, res) => {
  const authUrl = oauth2Client.generateAuthUrl({
    access_type: "offline",
    scope: [
      "https://www.googleapis.com/auth/youtube.upload",
      "https://www.googleapis.com/auth/youtube.force-ssl",
    ],
    prompt: "consent",
  });
  res.redirect(authUrl);
});

// ===============================
// AUTH CALLBACK
// ===============================
app.get("/auth/callback", async (req, res) => {
  try {
    const { code } = req.query;
    const { tokens } = await oauth2Client.getToken(code);
    oauth2Client.setCredentials(tokens);
    fs.writeFileSync(TOKEN_PATH, JSON.stringify(tokens, null, 2));
    res.send("✅ YouTube Connected Successfully. You can close this tab.");
  } catch (err) {
    res.status(500).send("Auth error: " + err.message);
  }
});

// ===============================
// YOUTUBE CLIENT
// ===============================
const youtube = google.youtube({
  version: "v3",
  auth: oauth2Client,
});

// ===============================
// UPLOAD ROUTE (manual video)
// ===============================
app.post("/upload", upload.single("video"), async (req, res) => {
  try {
    const { title, description } = req.body;

    const response = await youtube.videos.insert({
      part: "snippet,status",
      requestBody: {
        snippet: {
          title: title || "AIVANA Upload",
          description: description || "Uploaded via AIVANA Backend",
          categoryId: "28",
        },
        status: {
          privacyStatus: "public",
        },
      },
      media: {
        body: fs.createReadStream(req.file.path),
      },
    });

    res.json({
      success: true,
      videoId: response.data.id,
      url: `https://www.youtube.com/watch?v=${response.data.id}`,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===============================
// GENERATE + UPLOAD (AUTO PIPELINE)
// ===============================
app.post("/generate-and-upload", async (req, res) => {
  try {
    // Dummy auto video (small placeholder)
    const autoVideoPath = path.join(UPLOAD_DIR, "aivana-auto.txt");
    fs.writeFileSync(autoVideoPath, "AIVANA AUTO CONTENT");

    const response = await youtube.videos.insert({
      part: "snippet,status",
      requestBody: {
        snippet: {
          title: "AIVANA Auto Upload",
          description: "Auto-generated by AIVANA Universe",
          categoryId: "28",
        },
        status: {
          privacyStatus: "public",
        },
      },
      media: {
        body: fs.createReadStream(autoVideoPath),
      },
    });

    res.json({
      success: true,
      videoId: response.data.id,
      url: `https://www.youtube.com/watch?v=${response.data.id}`,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ===============================
// HEALTH CHECK
// ===============================
app.get("/", (req, res) => {
  res.send("🚀 AIVANA YouTube Backend is running");
});

// ===============================
// START SERVER
// ===============================
app.listen(PORT, () => {
  console.log(`🚀 Backend running on port ${PORT}`);
});
